# Generated by Django 3.0.6 on 2020-05-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
